[all] merge gateway & transfer, code refactor

diff --git a/modules/alarm/control b/modules/alarm/control
--- a/modules/alarm/control
+++ b/modules/alarm/control
@@ -64,27 +64,28 @@ function tailf() {
 }
 
 function build() {
-    go build
-    if [ $? -ne 0 ]; then
-        exit $?
+    go build -o $app main.go
+    sc=$?
+    if [ $sc -ne 0 ]; then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok" 
+        ./$app -v 
     fi
-    mv $module $app
-    ./$app -v | grep -v "config"
 }
 
 function pack() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v|grep -v config`
+    version=$(cat ../../VERSION)
     file_list="control cfg.example.json $app"
-    tar zcf $app-$version.tar.gz gitversion $file_list
+    tar zcf $app-$version.tar.gz $file_list
 }
 
 function packbin() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v|grep -v config`
-    tar zcvf $app-bin-$version.tar.gz $app gitversion
+    version=$(cat ../../VERSION)
+    tar zcvf $app-bin-$version.tar.gz $app
 }
 
 function help() {
diff --git a/modules/gateway/control b/modules/gateway/control
--- a/modules/gateway/control
+++ b/modules/gateway/control
@@ -1,98 +1,16 @@
 #!/bin/bash
-workspace=$(cd $(dirname $0) && pwd)
-cd $workspace
+
+WORKSPACE=$(cd $(dirname $0)/; pwd)
+cd $WORKSPACE
+
+mkdir -p var
 
 module=gateway
 app=falcon-$module
 conf=cfg.json
 pidfile=var/app.pid
 logfile=var/app.log
-gitversion=.gitversion
-pfc=perfcounter.json
 
-mkdir -p var &>/dev/null
-
-
-## build & pack
-function build() {
-    update_gitversion
-    go build -o $app main.go
-    sc=$?
-    if [ $sc -ne 0 ];then
-        echo "build error"
-        exit $sc
-    else
-        echo -n "build ok, vsn=" 
-        version
-    fi
-}
-
-function pack() {
-    build
-    version=`./$app -v`
-    tar zcvf $app-$version.tar.gz control $app cfg.example.json $pfc $gitversion ./test/debug
-}
-
-function packbin() {
-    build
-    version=`./$app -v`
-    tar zcvf $app-bin-$version.tar.gz $app $gitversion
-}
-
-## opt
-function start() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app started, pid="
-        cat $pidfile
-        return 1
-    fi
-
-    nohup ./$app -c $conf >>$logfile 2>&1 &
-    echo $! > $pidfile
-    echo "$app start ok, pid=$!"
-}
-
-function stop() {
-    pid=`cat $pidfile`
-    kill $pid
-    echo "$app stopped"
-}
-
-function restart() {
-    stop && sleep 1 && start
-}
-
-function reload() {
-    build && stop && sleep 1 && start && sleep 1 && printf "\n"  && tailf
-}
-
-## other
-function status() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app running, pid="
-        cat $pidfile
-    else
-        echo "$app stopped"
-    fi
-}
-
-function version() {
-    v=`./$app -v`
-    if [ -f $gitversion ];then
-        g=`cat $gitversion`
-    fi
-    echo "$v $g"
-}
-
-function tailf() {
-    tail -f $logfile
-}
-
-## internal
 function check_pid() {
     if [ -f $pidfile ];then
         pid=`cat $pidfile`
@@ -104,52 +22,96 @@ function check_pid() {
     return 0
 }
 
-function update_gitversion() {
-    git log -1 --pretty=%h > $gitversion
+function start() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "$app now is running already, pid="
+        cat $pidfile
+        return 1
+    fi
+
+    nohup ./$app -c $conf &> $logfile &
+    echo $! > $pidfile
+    echo "$app started..., pid=$!"
 }
 
-## usage
-function usage() {
-    echo "$0 build|pack|packbin|start|stop|restart|reload|status|tail|version"
+function stop() {
+    pid=`cat $pidfile`
+    kill -9 $pid
+    echo "$app stopped..."
 }
 
-## main
-action=$1
-case $action in
-    ## build
-    "build" )
-        build
-        ;;
-    "pack" )
-        pack
-        ;;
-    "packbin" )
-        packbin
-        ;;
-    ## opt
-    "start" )
-        start
-        ;;
-    "stop" )
-        stop
-        ;;
-    "restart" )
-        restart
-        ;;
-    "reload" )
-        reload
-        ;;
-    ## other
-    "status" )
-        status
-        ;;
-    "version" )
-        version
-        ;;
-    "tail" )
-        tailf
-        ;;
-    * )
-        usage
-        ;;
-esac
+function restart() {
+    stop
+    sleep 1
+    start
+}
+
+function status() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "$app now is running, pid="
+        cat $pidfile
+    else
+        echo "$app is stopped"
+    fi
+}
+
+function tailf() {
+    tail -f $logfile
+}
+
+function build() {
+    sed -i -e "s/Transfer/Gateway/g" ../transfer/g/g.go
+	find ./ -type f -name "g.go-e" -exec rm -f {} \;
+    go build -o $app ../transfer/main.go
+    sc=$?
+    if [ $sc -ne 0 ]; then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok" 
+        ./$app -v 
+    fi
+}
+
+function pack() {
+    build
+    version=$(cat ../../VERSION)
+    tar zcvf $app-$version.tar.gz control $app cfg.example.json
+}
+
+function packbin() {
+    build
+    version=$(cat ../../VERSION)
+    tar zcvf $app-bin-$version.tar.gz $app
+}
+
+
+function help() {
+    echo "$0 build|pack|packbin|start|stop|restart|status|tail"
+}
+
+if [ "$1" == "" ]; then
+    help
+elif [ "$1" == "stop" ];then
+    stop
+elif [ "$1" == "start" ];then
+    start
+elif [ "$1" == "restart" ];then
+    restart
+elif [ "$1" == "status" ];then
+    status
+elif [ "$1" == "tail" ];then
+    tailf
+elif [ "$1" == "build" ];then
+    build
+elif [ "$1" == "packbin" ];then
+    packbin
+elif [ "$1" == "pack" ];then
+    pack
+else
+    help
+fi
diff --git a/modules/judge/control b/modules/judge/control
--- a/modules/judge/control
+++ b/modules/judge/control
@@ -80,26 +80,27 @@ function tailf() {
 }
 
 function build() {
-    go build
-    if [ $? -ne 0 ]; then
-        exit $?
+    go build -o $app main.go
+    sc=$?
+    if [ $sc -ne 0 ]; then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok" 
+        ./$app -v 
     fi
-    mv $module $app
-    ./$app -v
 }
 
 function pack() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-$version.tar.gz control $app cfg.example.json gitversion
+    version=$(cat ../../VERSION)
+    tar zcvf $app-$version.tar.gz control $app cfg.example.json
 }
 
 function packbin() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-bin-$version.tar.gz $app gitversion
+    version=$(cat ../../VERSION)
+    tar zcvf $app-bin-$version.tar.gz $app
 }
 
 function help() {
diff --git a/modules/transfer/control b/modules/transfer/control
--- a/modules/transfer/control
+++ b/modules/transfer/control
@@ -64,33 +64,29 @@ function tailf() {
 }
 
 function build() {
-    commit=$(git log -1 --pretty=%h)
-    cat <<EOF > ./g/git.go
-package g
-const (
-    COMMIT = "$commit"
-)
-EOF
+    sed -i -e "s/Gateway/Transfer/g" g/g.go
+	find ./ -type f -name "g.go-e" -exec rm -f {} \;
     go build -o $app main.go
-    show_version
-}
-
-function show_version() {
-    ./$app -vg
+    sc=$?
+    if [ $sc -ne 0 ]; then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok" 
+        ./$app -v 
+    fi
 }
 
 function pack() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-$version.tar.gz control $app cfg.example.json gitversion ./test/debug
+    version=$(cat ../../VERSION)
+    tar zcvf $app-$version.tar.gz control $app cfg.example.json ./test/debug
 }
 
 function packbin() {
     build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-bin-$version.tar.gz $app gitversion
+    version=$(cat ../../VERSION)
+    tar zcvf $app-bin-$version.tar.gz $app
 }
 
 
diff --git a/modules/updater/control b/modules/updater/control
--- a/modules/updater/control
+++ b/modules/updater/control
@@ -5,8 +5,8 @@ cd $WORKSPACE
 
 mkdir -p var
 
-module=updater-https
-app=ops-$module
+module=updater
+app=falcon-$module
 conf=cfg.json
 pidfile=var/app.pid
 logfile=var/app.log
@@ -63,23 +63,26 @@ function tailf() {
 }
 
 function build() {
-    go build -a
-    if [ $? -ne 0 ]; then
-        exit $?
+    go build -o $app main.go
+    sc=$?
+    if [ $sc -ne 0 ]; then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok" 
+        ./$app -v 
     fi
-    mv $module $app
-    ./$app -v
 }
 
 function pack() {
     build
-    version=`./$app -v`
+    version=$(cat ../../VERSION)
     tar zcvf $app-$version.tar.gz control cfg.example.json $app
 }
 
 function packbin() {
     build
-    version=`./$app -v`
+    version=$(cat ../../VERSION)
     tar zcvf $app-bin-$version.tar.gz $app
 }
 
